'use client'

import { cn } from '@/lib/utils'
import type { Enrichment } from '@td2u/shared-types'
import { getSafeUrl } from '@td2u/shared-validations'

interface EnrichmentPreviewProps {
  enrichment: Enrichment
  className?: string
}

export function EnrichmentPreview({
  enrichment,
  className,
}: EnrichmentPreviewProps) {
  // Null safety for all fields
  const summary = enrichment?.summary ?? ''
  const examples = enrichment?.examples ?? []
  const relatedTerms = enrichment?.related_terms ?? []
  const referenceLinks = enrichment?.reference_links ?? []
  const translationJa = enrichment?.translation_ja ?? ''
  const translationEn = enrichment?.translation_en ?? ''
  const model = enrichment?.model ?? 'unknown'
  const generatedAt = enrichment?.generated_at ?? new Date().toISOString()

  return (
    <div className={cn('space-y-6', className)}>
      {/* Translations */}
      <div className="grid md:grid-cols-2 gap-4">
        <div className="bg-blue-50 rounded-lg p-4">
          <h4 className="text-xs font-medium text-blue-700 mb-1">Japanese</h4>
          <p className="text-lg text-blue-900">{translationJa || 'N/A'}</p>
        </div>
        <div className="bg-green-50 rounded-lg p-4">
          <h4 className="text-xs font-medium text-green-700 mb-1">English</h4>
          <p className="text-lg text-green-900">{translationEn || 'N/A'}</p>
        </div>
      </div>

      {/* Summary */}
      {summary && (
        <div>
          <h4 className="text-sm font-medium text-gray-900 mb-2">Summary</h4>
          <div className="bg-gray-50 rounded-lg p-4">
            {summary.split('\n').map((line, index) => (
              <p key={index} className="text-gray-700">
                {line}
              </p>
            ))}
          </div>
        </div>
      )}

      {/* Examples */}
      {examples.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-900 mb-2">Examples</h4>
          <ul className="space-y-2">
            {examples.map((example, index) => (
              <li
                key={index}
                className="flex items-start gap-2 text-gray-700"
              >
                <span className="text-primary-500 mt-1">-</span>
                <span>{example}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Related Terms */}
      {relatedTerms.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-900 mb-2">Related Terms</h4>
          <div className="flex flex-wrap gap-2">
            {relatedTerms.map((term, index) => (
              <span
                key={index}
                className="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm"
              >
                {term}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* References */}
      {referenceLinks.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-900 mb-2">References</h4>
          <ul className="space-y-1">
            {referenceLinks.map((link, index) => {
              // Only render links with safe URLs (http/https)
              const safeUrl = getSafeUrl(link.url)
              if (!safeUrl) return null

              return (
                <li key={index}>
                  <a
                    href={safeUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary-600 hover:underline text-sm"
                  >
                    {link.title}
                  </a>
                </li>
              )
            })}
          </ul>
        </div>
      )}

      {/* Generation info */}
      <div className="text-xs text-gray-400 pt-4 border-t">
        Generated by {model} on{' '}
        {new Date(generatedAt).toLocaleDateString()}
      </div>
    </div>
  )
}
